images/urls.py
from django.urls import path
from .views import (
    UserImageListView,
    CreateNewimageView,
    SearchImageView,
    DeleteImage,
    ImageDetailView,
    LandingToImage,
)


app_name = 'images'
urlpatterns = [
    path('', UserImageListView.as_view(), name='user-images-list'),
    path('image/<int:pk>/', ImageDetailView.as_view(), name='detail-image'),
    path('create-image/<int:pk>/', CreateNewimageView.as_view(), name='create-image'),
    path('delete-image/<int:pk>/', DeleteImage.as_view(), name='delete-image'),
    path('search-image/', SearchImageView.as_view(), name='search-image'),
    path('landing-to-image/', LandingToImage.as_view(), name='landing-to-image'),
]

mlm_builder/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.views.generic import TemplateView

from landing.views import LandingDetailView
from mlm_builder.settings import MEDIA_URL, MEDIA_ROOT, DEBUG
from django.conf.urls.static import static
from dashboard_home.views import DashboardView
from webinar.views import WebinarPublicDetailView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('dashboard/', include([
        path('', DashboardView.as_view(), name='dashboard'),
        path('profile/', include('profile_mlm.urls')),
        path('webinar/', include('webinar.urls')),
        path('packages/', include('package.urls')),
        path('lending/', include('landing.urls')),
        path('images/', include('images.urls')),
    ])),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('l/<int:pk>/<slug:webinar_slug>/', LandingDetailView.as_view(), name='webinar-view'),
    path('l/<int:pk>/<slug:webinar_slug>/<int:image_pk>/', LandingDetailView.as_view(), name='webinar-view'),
    path('w/<slug:code>/', WebinarPublicDetailView.as_view(), name='publick-webinar'),
    re_path(r'^datetimepicker/', include('datetimepicker.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)


if DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

profile_mlm/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from .views import (
    logout_view,
    ProfileDetailView,
    AuthView,
    ProfileEditView,
)


app_name = 'profile'
urlpatterns = [
    path('login/', AuthView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('', ProfileDetailView.as_view(), name='detail'),
    path('edit/', ProfileEditView.as_view(), name='edit'),
]

profile_mlm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext as _
from mlm_builder.utils import set_filename
from ckeditor_uploader.fields import RichTextUploadingField
from phonenumber_field.modelfields import PhoneNumberField
from sorl.thumbnail.fields import ImageField
from package.models import Package
from mlm_builder.basemodel import BaseModel
from webinar.models import Webinar
from landing.models import Landing


def set_default_package():
    try:
        return Package.objects.get(is_start_package=True).id
    except Package.DoesNotExist:
        return None


class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = ImageField(verbose_name=_('Аватар'), upload_to=set_filename, blank=True, null=True, default=None)
    description = RichTextUploadingField(verbose_name=_('Обо мне'), blank=True, default='')
    is_push_email = models.BooleanField(verbose_name=_('Получать Email уведомления'), default=True)
    website = models.URLField(verbose_name=_('Сайт'), blank=True)
    phone = PhoneNumberField(verbose_name=_('Телефон'), max_length=30, blank=True)
    skype = models.CharField(verbose_name=_('Логин в Skype'), max_length=150, blank=True)

    balance = models.DecimalField(verbose_name='Баланс', max_digits=10, decimal_places=2, default=0)

    link_vkontakte = models.URLField(verbose_name=_('Ссылка на страницу ВКонтакте'), blank=True)
    link_facebook = models.URLField(verbose_name=_('Ссылка на страницу Facebook'), blank=True)
    link_twitter = models.URLField(verbose_name=_('Ссылка на страницу Twitter'), blank=True)
    link_instagram = models.URLField(verbose_name=_('Ссылка на страницу Instagram'), blank=True)
    link_odnoklassniki = models.URLField(verbose_name=_('Ссылка на страницу Одноклассники'), blank=True)
    link_my_world = models.URLField(verbose_name=_('Ссылка на страницу Мой мир'), blank=True)

    package = models.ForeignKey(Package, verbose_name='Тарифный план', on_delete=models.SET_DEFAULT, default=set_default_package, blank=True, null=True)
    package_end_date = models.DateTimeField(verbose_name='Дата окончания тарифа', blank=True, null=True)

    class Meta:
        verbose_name = _('Профиль пользователя')
        verbose_name_plural = _('Профили пользователей')

    def __str__(self):
        return self.user.username

    def is_can_create_webinar(self):
        """
        Проверка может ли пользователь добавлять новые вебинары
        :return: bool
        """
        if self.package is None:
            return False

        exist_webinars_count = Webinar.objects.filter(owner=self.user).count()
        webinar_limit = self.package.max_webinars

        if webinar_limit > exist_webinars_count or webinar_limit == -1:
            return True
        return False

    def is_can_create_lending_to_webinar(self, webinar):
        """
        Проверка может ли пользователь добавлять новые дендинги к вебинарам
        :return: bool
        """
        if self.package is None:
            return False

        exist_landing_to_webinar_count = Landing.objects.filter(
            owner=self.user,
            webinar=webinar,
        ).count()
        lendings_limit = self.package.max_lending_to_webinar

        if lendings_limit > exist_landing_to_webinar_count or lendings_limit == -1:
            return True
        return False

    def is_can_create_premium_template(self):
        return self.package.can_create_premium_template


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

profile_mlm/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.validators import validate_slug
from phonenumber_field.formfields import PhoneNumberField
from ckeditor.widgets import CKEditorWidget


class AuthForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.PasswordInput()

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class ProfileEditForm(forms.Form):
    first_name = forms.CharField(label='Имя')
    last_name = forms.CharField(label='Фамилия', required=False)
    email = forms.EmailField(label='Email')
    avatar = forms.ImageField(label='Аватар', required=False)
    website = forms.URLField(label='Сайт', required=False)
    phone = PhoneNumberField(label='Телефон', required=False)
    skype = forms.CharField(label='Skype', required=False, validators=[validate_slug])
    birth_date = forms.DateField(label='День рожденья', required=False)
    link_vkontakte = forms.URLField(label='VK', required=False)
    link_facebook = forms.URLField(label='FACEBOOK', required=False)
    link_twitter = forms.URLField(label='TWITTER', required=False)
    link_instagram = forms.URLField(label='INSTAGRAM', required=False)
    link_odnoklassniki = forms.URLField(label='ODNOKLASNIKI', required=False)
    link_my_world = forms.URLField(label='МОЙ МИР', required=False)
    description = forms.CharField(widget=CKEditorWidget(), label='Обо мне', required=False)

    def __init__(self, *args, **kwargs):
        self.desc_init = kwargs.pop('desc_init', None)
        super(ProfileEditForm, self).__init__(*args, **kwargs)
        self.initial['description'] = self.desc_init

profile_mlm/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import (
    logout,
    authenticate,
    login,
)
from .models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView
from .forms import (
    AuthForm,
    ProfileEditForm,
)
from django.views.generic import FormView
from mlm_builder.utils import set_filename
from django.core.files.storage import FileSystemStorage


def logout_view(request):
    logout(request)
    return redirect(reverse_lazy('profile:login'))


class ProfileDetailView(LoginRequiredMixin, DetailView):
    template_name = 'profile_mlm/profile.html'
    context_object_name = 'profile'

    def get_object(self, queryset=None):
        return Profile.objects.select_related('user').get(user=self.request.user)


class AuthView(FormView):
    form_class = AuthForm
    template_name = 'profile_mlm/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse_lazy('dashboard'))

        return super(AuthView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(self.request, user)
                return redirect(reverse_lazy('dashboard'))


class ProfileEditView(LoginRequiredMixin, FormView):
    form_class = ProfileEditForm
    template_name = 'profile_mlm/edit.html'
    success_url = reverse_lazy('profile:detail')

    def get_form_kwargs(self):
        kwargs = super(ProfileEditView, self).get_form_kwargs()
        desc_init = self.request.user.profile.description
        if desc_init:
            kwargs['desc_init'] = self.request.user.profile.description
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = Profile.objects.get(user=self.request.user)
        return context

    def form_valid(self, form):
        user = self.request.user

        avatar_file = self.request.FILES.get('avatar')
        if avatar_file:
            filename = set_filename(None, avatar_file.name)
            fs = FileSystemStorage()
            file_name = fs.save(filename, avatar_file)
            user.profile.avatar = file_name
            user.save()
            return super().form_valid(form)

        user.first_name = form.cleaned_data.get('first_name')
        user.last_name = form.cleaned_data.get('last_name')
        user.email = form.cleaned_data.get('email')
        user.profile.description = form.cleaned_data.get('description')

        user.profile.description = form.cleaned_data.get('description')
        user.profile.phone = form.cleaned_data.get('phone')
        user.profile.website = form.cleaned_data.get('website')
        user.profile.skype = form.cleaned_data.get('skype')

        user.profile.link_vkontakte = form.cleaned_data.get('link_vkontakte')
        user.profile.link_facebook = form.cleaned_data.get('link_facebook')
        user.profile.link_twitter = form.cleaned_data.get('link_twitter')
        user.profile.link_instagram = form.cleaned_data.get('link_instagram')
        user.profile.link_odnoklassniki = form.cleaned_data.get('link_odnoklassniki')
        user.profile.link_my_world = form.cleaned_data.get('link_my_world')

        user.save()

        return super().form_valid(form)

profile_mlm/templates/profile_mlm/edit.html
{% extends 'theme_2.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
    <div id="clearFocuse" class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card card-shadow">
                <div class="card-header">
                    <div class="card-title">Редактировать профиль пользователя</div>
                </div>
                <div class="card-body">

                    <form action="" method="post">
                                {% csrf_token %}

                                <h3 class="text-center col-pink" style="margin-bottom: 50px;">Основная информация</h3>

                                <div class="row clearfix">
                                    <div class="col-md-6">
                                        <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.first_name.errors %}error{% endif %}">
                                                {% render_field form.first_name class='form-control' placeholder='Имя' value=profile.user.first_name %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.first_name.errors %}error{% endif %}">
                                                {% render_field form.last_name class='form-control' placeholder='Фамилия' value=profile.user.last_name %}
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                    <div class="col-md-6">
                                        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.email.errors %}error{% endif %}">
                                                {% render_field form.email class='form-control' placeholder='Email' value=profile.user.email %}
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.email.errors }}</div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                    <div class="col-md-4">
                                        <label for="{{ form.skype.id_for_label }}">{{ form.skype.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.skype.errors %}error{% endif %}">
                                                {% render_field form.skype class='form-control' placeholder='Skype' value=profile.skype %}
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.skype.errors }}</div>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.phone.errors %}error{% endif %}">
                                                {% render_field form.phone class='form-control phone' placeholder='+__ (___) ___-__-__' value=profile.phone %}
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.phone.errors }}</div>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="{{ form.website.id_for_label }}">{{ form.website.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.website.errors %}error{% endif %}">
                                                {% render_field form.website class='form-control' placeholder='Сайт' value=profile.website %}
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.website.errors }}</div>
                                    </div>
                                </div>

                                <h3 class="text-center col-pink" style="margin-bottom: 50px;">Профили в социальных сетях</h3>

                                <div class="row clearfix">
                                    <div class="col-md-4">
                                        <label for="{{ form.link_vkontakte.id_for_label }}">{{ form.link_vkontakte.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.link_vkontakte.errors %}error{% endif %}">
                                                {% render_field form.link_vkontakte class='form-control' placeholder='Профиль VK' value=profile.link_vkontakte %}
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.link_vkontakte.errors }}</div>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="{{ form.link_facebook.id_for_label }}">{{ form.link_facebook.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.link_facebook.errors %}error{% endif %}">
                                                {% render_field form.link_facebook class='form-control' placeholder='Профиль FACEBOOK' value=profile.link_facebook %}
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.link_facebook.errors }}</div>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="{{ form.link_my_world.id_for_label }}">{{ form.link_my_world.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.link_my_world.errors %}error{% endif %}">
                                                {% render_field form.link_my_world class='form-control' placeholder='Профиль МОЙ МИР' value=profile.link_my_world %}
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.link_my_world.errors }}</div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                    <div class="col-md-4">
                                        <label for="{{ form.link_twitter.id_for_label }}">{{ form.link_twitter.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.link_twitter.errors %}error{% endif %}">
                                                {% render_field form.link_twitter class='form-control' placeholder='Профиль TWITTER' value=profile.link_twitter %}
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.link_twitter.errors }}</div>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="{{ form.link_instagram.id_for_label }}">{{ form.link_instagram.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.link_instagram.errors %}error{% endif %}">
                                                {% render_field form.link_instagram class='form-control' placeholder='Профиль INSTAGRAM' value=profile.link_instagram %}
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.link_instagram.errors }}</div>
                                    </div>
                                    <div class="col-md-4">
                                        <label for="{{ form.link_odnoklassniki.id_for_label }}">{{ form.link_odnoklassniki.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.link_odnoklassniki.errors %}error{% endif %}">
                                                {% render_field form.link_odnoklassniki class='form-control' placeholder='Профиль ODNOKLASNIKI' value=profile.link_odnoklassniki %}
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.link_odnoklassniki.errors }}</div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                    <div class="col-md-12">
                                        <label for="{{ form.description.id_for_label }}">{{ form.description.label }}</label>
                                        <div class="form-group">
                                            <div class="form-line {% if form.description.errors %}error{% endif %}">
                                                {{ form.description }}
                                                <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
                                                <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
                                            </div>
                                        </div>
                                        <div class="error forms__errors">{{ form.description.errors }}</div>
                                    </div>
                                </div>

                                <button class="btn btn-primary btn-lg waves-effect">Сохранить изменения</button>
                            </form>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer_scripts %}

{% endblock %}

profile_mlm/templates/profile_mlm/profile.html
{% extends 'theme_2.html' %}
{% load static %}

{% block content %}
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card card-shadow">
                <div class="card-header">
                    <div class="card-title">Профиль пользователя
                        {#                    <ul class="header-dropdown m-r--5">#}
                        {#                        <li class="dropdown">#}
                        {#                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button"#}
                        {#                               aria-haspopup="true" aria-expanded="true">#}
                        {#                                <i class="material-icons">more_vert</i>#}
                        {#                            </a>#}
                        {#                            <ul class="dropdown-menu pull-right">#}
                        {#                                <li><a href="{% url 'profile:edit' %}"#}
                        {#                                       class=" waves-effect waves-block">Редактировать</a></li>#}
                        {#                            </ul>#}
                        {#                        </li>#}
                        {#                    </ul>#}
                        <div class="btn-group float-right task-list-action">
                            <div class="dropdown">
                                <a href="#" class="btn btn-transparent default-color dropdown-hover p-0"
                                   data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class=" icon-options"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" x-placement="bottom-end"
                                     style="position: absolute; transform: translate3d(-144px, 29px, 0px); top: 0px; left: 0px; will-change: transform;">
                                    <a class="dropdown-item" href="{% url 'profile:edit' %}"> <i
                                            class="icon-pencil text-info pr-2"></i>Редактировать</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="profile__avatar__wrapper text-center">
                        {% if profile.avatar %}
                            <img class="profile__avatar img-thumbnail" src="{{ profile.avatar.url }}"
                                 alt="{{ user.get_full_name }}">
                        {% else %}
                            <img class="profile__avatar img-thumbnail" src="{% static '/' %}user.png"
                                 alt="{{ user.get_full_name }}">
                        {% endif %}
                        <h1>{{ profile.user.username }}<br>
                            <small>{{ profile.user.get_full_name }}</small>
                        </h1>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table table-bordered table-hover table-striped">
                                <tr>
                                    <td>Сайт</td>
                                    <td><a href="{{ profile.website }}" target="_blank">{{ profile.website }}</a></td>
                                </tr>
                                <tr>
                                    <td>Телефон</td>
                                    <td>{{ profile.phone }}</td>
                                </tr>
                                <tr>
                                    <td>Skype</td>
                                    <td><a href="skype:{{ profile.skype }}?call">{{ profile.skype }}</a></td>
                                </tr>
                                <tr>
                                    <td>Профиль VK</td>
                                    <td>{{ profile.link_vkontakte }}</td>
                                </tr>
                                <tr>
                                    <td>Профиль FACEBOOKе</td>
                                    <td>{{ profile.link_facebook }}</td>
                                </tr>
                                <tr>
                                    <td>Профиль TWITTER</td>
                                    <td>{{ profile.link_twitter }}</td>
                                </tr>
                                <tr>
                                    <td>Профиль INSTAGRAM</td>
                                    <td>{{ profile.link_instagram }}</td>
                                </tr>
                                <tr>
                                    <td>Профиль ODNOKLASNIKI</td>
                                    <td>{{ profile.link_odnoklassniki }}</td>
                                </tr>
                                <tr>
                                    <td>Профиль МОЙ МИР</td>
                                    <td>{{ profile.link_my_world }}</td>
                                </tr>
                            </table>
                        </div>
                        <div class="col-md-12">
                            <h3 class="text-center">Обо мне</h3>
                            <hr>
                            {{ profile.description | safe }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}