images/urls.py
from django.urls import path
from .views import (
    UserImageListView,
    CreateNewimageView,
    SearchImageView,
    DeleteImage,
    ImageDetailView,
    LandingToImage,
)


app_name = 'images'
urlpatterns = [
    path('', UserImageListView.as_view(), name='user-images-list'),
    path('image/<int:pk>/', ImageDetailView.as_view(), name='detail-image'),
    path('create-image/<int:pk>/', CreateNewimageView.as_view(), name='create-image'),
    path('delete-image/<int:pk>/', DeleteImage.as_view(), name='delete-image'),
    path('search-image/', SearchImageView.as_view(), name='search-image'),
    path('landing-to-image/', LandingToImage.as_view(), name='landing-to-image'),
]

landing/urls.py
from django.urls import path
from .views import (
    LandingListView,
    LandingDeleteView,
    LandingEditView,
    LandingCreatePremium,
    LandingEditPremium,
)


app_name = 'landing'
urlpatterns = [
    path('<int:pk>', LandingEditView.as_view(), name='detail'),
    path('create/<int:webinar_pk>', LandingCreatePremium.as_view(), name='create'),
    path('edit/<int:pk>/', LandingEditPremium.as_view(), name='edit'),
    path('', LandingListView.as_view(), name='list'),
    path('<int:pk>/delete', LandingDeleteView.as_view(), name='delete'),
]

mlm_builder/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.views.generic import TemplateView

from landing.views import LandingDetailView
from mlm_builder.settings import MEDIA_URL, MEDIA_ROOT, DEBUG
from django.conf.urls.static import static
from dashboard_home.views import DashboardView
from webinar.views import WebinarPublicDetailView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('dashboard/', include([
        path('', DashboardView.as_view(), name='dashboard'),
        path('profile/', include('profile_mlm.urls')),
        path('webinar/', include('webinar.urls')),
        path('packages/', include('package.urls')),
        path('lending/', include('landing.urls')),
        path('images/', include('images.urls')),
    ])),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('l/<int:pk>/<slug:webinar_slug>/', LandingDetailView.as_view(), name='webinar-view'),
    path('l/<int:pk>/<slug:webinar_slug>/<int:image_pk>/', LandingDetailView.as_view(), name='webinar-view'),
    path('w/<slug:code>/', WebinarPublicDetailView.as_view(), name='publick-webinar'),
    re_path(r'^datetimepicker/', include('datetimepicker.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)


if DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

package/urls.py
from django.urls import path
from .views import (
    PackageListView,
)


app_name = 'package'
urlpatterns = [
    path('', PackageListView.as_view(), name='list'),
]

webinar/urls.py
from django.urls import path
from .views import (
    WebinarListView,
    WebinarDetailView,
    WebinarUpdateView,
    WebinarCreateView,
    WebinarDeleteView,
)


app_name = 'webinar'
urlpatterns = [
    path('', WebinarListView.as_view(), name='my_webinars'),
    path('<slug:slug>/<int:owner_pk>', WebinarDetailView.as_view(), name='detail'),
    path('<slug:slug>/update', WebinarUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete', WebinarDeleteView.as_view(), name='delete'),
    path('create', WebinarCreateView.as_view(), name='create'),
]

templates/partials/_left_nav.html
{% load landing_tags %}

<ul id="nav-accordion">
    <li>
        <a href="{% url 'dashboard' %}">
            <i class="fa fa-dashboard"></i>
            <span>Главная</span>
        </a>
    </li>

    <li class="nav-title">
        <h5 class="text-uppercase">Components</h5>
    </li>

    <li>
        <a href="{% url 'package:list' %}">
            <i class="fa fa-money"></i>
            <span>Тарифы</span>
        </a>
    </li>

    {% if user.is_active %}

        <li class="sub-menu">
            <a href="javascript:;">
                <i class="fa fa-video-camera"></i>
                <span>Вебинары</span>
            </a>
            <ul class="sub">
                <li><a href="{% url 'webinar:my_webinars' %}">Мои вебинары</a></li>
                <li><a href="{% url 'webinar:create' %}">Добавить вебинар</a></li>
            </ul>
        </li>


        <li class="sub-menu">
            <a href="javascript:;">
                <i class="fa fa-sitemap"></i>
                <span>Лендинги</span>
            </a>
            <ul class="sub">
                <li><a href="{% url 'landing:list' %}">Мои лендинги</a></li>
            </ul>
        </li>

        <li class="sub-menu">
            <a href="javascript:;">
                <i class="fa  fa-file-image-o"></i>
                <span>Изображения</span>
            </a>
            <ul class="sub">
                <li><a href="{% url 'images:user-images-list' %}">Мои картинки</a></li>
                <li><a href="{% url 'images:search-image' %}">Найти картинку</a></li>
{#                <li><a href="{% url 'images:create-image' %}">Создать новую картинку</a></li>#}
            </ul>
        </li>

    {% endif %}

</ul>