images/urls.py
from django.urls import path
from .views import (
    UserImageListView,
    CreateNewimageView,
    SearchImageView,
    DeleteImage,
    ImageDetailView,
    LandingToImage,
)


app_name = 'images'
urlpatterns = [
    path('', UserImageListView.as_view(), name='user-images-list'),
    path('image/<int:pk>/', ImageDetailView.as_view(), name='detail-image'),
    path('create-image/<int:pk>/', CreateNewimageView.as_view(), name='create-image'),
    path('delete-image/<int:pk>/', DeleteImage.as_view(), name='delete-image'),
    path('search-image/', SearchImageView.as_view(), name='search-image'),
    path('landing-to-image/', LandingToImage.as_view(), name='landing-to-image'),
]

mlm_builder/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.views.generic import TemplateView

from landing.views import LandingDetailView
from mlm_builder.settings import MEDIA_URL, MEDIA_ROOT, DEBUG
from django.conf.urls.static import static
from dashboard_home.views import DashboardView
from webinar.views import WebinarPublicDetailView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('dashboard/', include([
        path('', DashboardView.as_view(), name='dashboard'),
        path('profile/', include('profile_mlm.urls')),
        path('webinar/', include('webinar.urls')),
        path('packages/', include('package.urls')),
        path('lending/', include('landing.urls')),
        path('images/', include('images.urls')),
    ])),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('l/<int:pk>/<slug:webinar_slug>/', LandingDetailView.as_view(), name='webinar-view'),
    path('l/<int:pk>/<slug:webinar_slug>/<int:image_pk>/', LandingDetailView.as_view(), name='webinar-view'),
    path('w/<slug:code>/', WebinarPublicDetailView.as_view(), name='publick-webinar'),
    re_path(r'^datetimepicker/', include('datetimepicker.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)


if DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

images/models.py
from django.db import models
from mlm_builder.basemodel import BaseModel
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string
from landing.models import Landing


def set_image_name(instanse, filename):
    name = get_random_string(20)
    ext = filename.split('.')[-1]
    path = 'images/{}__{}.{}'.format(instanse.pk, name, ext)
    return path


class UserImage(BaseModel):
    """
    Пользовательские вирусные картинки
    """
    title = models.CharField(max_length=200, verbose_name='Название')
    image = models.ImageField(verbose_name='Изображение', upload_to=set_image_name)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    landing = models.ManyToManyField(
        Landing, verbose_name='Лендинги', through='LandingImage', through_fields=('userimage', 'langing')
    )

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

    def __str__(self):
        return self.title

    @property
    def count_landings(self):
        return self.landing.count()

    def get_landingimages(self):
        landingimages = LandingImage.objects.filter(
            userimage=self,
        )
        return landingimages


class LandingImage(BaseModel):
    langing = models.ForeignKey(Landing, on_delete=models.CASCADE)
    userimage = models.ForeignKey(UserImage, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    email_counter = models.PositiveIntegerField(default=0)

    def __str__(self):
        return '{} - {}'.format(self.langing, self.userimage)

images/views.py
import os
from django.contrib import messages
from django.http import Http404, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from landing.models import Landing
from .models import UserImage, LandingImage
from django.views.generic import ListView, DetailView
import requests
import json
from binascii import a2b_base64
from mlm_builder.settings import MEDIA_ROOT


class UserImageListView(ListView):
    """
    Список картинок пользователя
    """
    template_name = 'images/user-images-list-view.html'
    context_object_name = 'images'

    def get_queryset(self):
        return UserImage.objects.filter(owner=self.request.user)

    def get(self, *args, **kwargs):
        image_id = self.request.GET.get('get_image_info')
        if image_id:

            try:
                user_image = UserImage.objects.prefetch_related('landing').get(id=image_id)
            except UserImage.DoesNotExist:
                return Http404()

            context = {
                'landings': []
            }
            for landing in user_image.landing.all():
                landing_image = LandingImage.objects.get(langing=landing, userimage_id=image_id)
                context['landings'].append({
                    'id': landing.id,
                    'title': landing.title,
                    'link': landing.get_absolute_url(),
                    'image_id': image_id,
                    'set_title': landing_image.title,
                    'set_description': landing_image.description,
                })

            return JsonResponse(context)

        return super(UserImageListView, self).get(args, kwargs)


class ImageDetailView(DetailView):
    template_name = 'images/image-detail.html'
    context_object_name = 'image'

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        image = UserImage.objects.get(pk=pk)
        return image

    def post(self, *args, **kwargs):

        if self.request.POST.get('imageToLanding'):
            data = [
                {
                    'id': 0,
                    'text': 'Выберите лендинг',
                    'disabled': True,
                    'selected': True
                }
            ]

            landingimages = [i['langing_id'] for i in LandingImage.objects.filter(
                userimage=self.get_object(),
            ).values('langing_id')]

            landings = Landing.objects.filter(
                owner=self.request.user
            )

            for landing in landings:
                data.append({
                    'id': landing.id,
                    'text': landing.title,
                    'disabled': True if landing.id in landingimages else False,
                })

            return JsonResponse({'data': data})

        response_data = {'success': 0}

        landing_id = self.request.POST.get('landing_id')
        image_id = self.request.POST.get('image_id')

        if landing_id and image_id:
            landing = get_object_or_404(Landing, pk=landing_id)
            image = get_object_or_404(UserImage, pk=image_id)
            landing_image = get_object_or_404(LandingImage, langing=landing, userimage=image)
            landing_image.delete()

            response_data.update({'success': 1})

        return JsonResponse(response_data)


class LandingToImage(View):
    """
    Связывание изображения и лендинга
    """

    def post(self, request):
        landing = get_object_or_404(Landing, pk=request.POST.get('landing'))
        image = get_object_or_404(UserImage, pk=request.POST.get('image'))
        title = request.POST.get('title')
        description = request.POST.get('description')

        landingimage = LandingImage(
            langing=landing,
            userimage=image,
            title=title,
            description=description,
        )
        landingimage.save()

        return redirect(request.META.get('HTTP_REFERER'))


class CreateNewimageView(DetailView):
    template_name = 'images/create-image.html'
    context_object_name = 'image'
    model = UserImage

    def post(self, request, pk):
        user_image = self.get_object()

        image_data_url = request.POST.get('imageData').split('data:image/png;base64,')[-1]
        binary_data = a2b_base64(image_data_url)
        filename = '{path}/{image_name}'.format(
            path=MEDIA_ROOT,
            image_name=user_image.image,
        )

        fd = open(filename, 'wb')
        fd.write(binary_data)
        fd.close()

        return JsonResponse({'status': 1})


class DeleteImage(View):
    """
    Удаление изображения из базы и из хранилища
    """

    def post(self, request, pk):
        print('-'*90)
        image = get_object_or_404(UserImage, id=pk)
        filename = image.image
        image.delete()

        path = MEDIA_ROOT + '/' + str(filename)
        os.remove(path)

        return JsonResponse({'status': True})


class SearchImageView(View):
    """
    Поиск картинок на Pixabey.com API 
    """

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(SearchImageView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        print('-'*80)

        print(request)
        if request.GET.get('action') == 'get_my_images':
            user_images = list(map(lambda x: x[0], UserImage.objects.filter(
                owner=request.user).values_list('image')))
            return JsonResponse({
                'status': True,
                'my_images': list(map(lambda x: int(x.split('__')[-1].split('.')[0]), user_images)),
            })

        return render(request, 'images/search-image.html')

    def post(self, request):
        url = json.loads(request.body.decode('utf-8')).get('url')
        image_id = json.loads(request.body.decode('utf-8')).get('image_id')

        if url:
            ext = self.get_file_ext(url)
            filename = self.make_filename(image_id, ext, self.request.user.id)

            user_images = list(map(lambda x: x[0], UserImage.objects.filter(owner=request.user).values_list('image')))

            if filename not in user_images:
                self.get_and_save_image(url, filename)

                image = UserImage(
                    owner=request.user,
                    image=filename,
                    title='Title not yet',
                )
                image.save()

                return JsonResponse({'status': True})

        return JsonResponse({'status': False})

    @staticmethod
    def get_and_save_image(url, filename):
        r = requests.get(url)
        if r.status_code == 200:
            with open('media/' + filename, 'wb') as file:
                file.write(r.content)

    @staticmethod
    def make_filename(pk, ext, user_id):
        return 'images/{}__{}.{}'.format(user_id, pk, ext)

    @staticmethod
    def get_file_ext(url):
        return url.split('.')[-1]

images/templates/images/image-detail.html
{% extends 'theme_2.html' %}
{% load thumbnail %}
{% load static %}

{% block page_name %}
    Список Ваших изображений
{% endblock %}

{% block page_small_name %}
    Каждая отправленная ссылка на лендинг с другим изображением повышает шанс получить нового партнёра. Действуй!
{% endblock %}

{% block help_link %}
    <a class="btn btn-outline-info" href="#">Как с этим работать?</a>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="col-md-12 imageCard">
            <div class="card mb-4 card-shadow">
                <div class="card-body">
                    <img src="{{ image.image.url }}" class="img-fluid rounded" style="margin: 0 auto; display: block;">
                    <div style="text-align: center; margin: 15px 0;">
                        <a href="#" class="btn btn-sm btn-outline-primary btn-lg" id="image-to-landing">Связать с новым лендингом</a>
                    </div>
                    {% for landingimage in image.get_landingimages %}
                        <table class="table table-bordered landing-row">
                            <tr>
                                <td>{{ landingimage.langing }}</td>
                                <td style="text-align: right; width: 30%; vertical-align: middle; text-align: center" rowspan="2">
                                    <a href="{{ landingimage.langing.get_absolute_url }}" class="btn btn-sm btn-info" target="_blank">Смотреть лендинг</a>
                                    <a href="#" class="btn btn-sm btn-danger delLanding" data-id="{{ landingimage.langing.id }}" data-image="{{ image.id }}">Отвязать лендинг</a>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div><span class="text-info">Заголовок:</span> {{ landingimage.title }}</div>
                                    <div><span class="text-info">Описание:</span> {{ landingimage.description }}</div>
                                </td>
                            </tr>
                        </table>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div id="MyLendingModal" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form action="{% url 'images:landing-to-image' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" value="{{ image.id }}" name="image">
                    <div class="modal-header">
                        <h5 class="modal-title">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="choiceLanding">Выберите лендинг</label>
                            <select name="landing" id="choiceLanding"></select>
                        </div>
                        <div class="form-group">
                            <label for="title">Заголовок</label>
                            <input type="text" name="title" value="" id="title" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="description">Описание</label>
                            <textarea name="description" id="description" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

{% block footer_scripts %}{% endblock footer_scripts %}

images/templates/images/search-image.html
{% extends 'theme_2.html' %}
{% load thumbnail %}
{% load static %}

{% block page_name %}
    Список Ваших изображений
{% endblock %}

{% block page_small_name %}
    Каждая отправленная ссылка на лендинг с другим изображением повышает шанс получить нового партнёра. Действуй!
{% endblock %}

{% block help_link %}
    <a class="btn btn-outline-info" href="#">Как с этим работать?</a>
{% endblock %}

{% block content %}
    {% csrf_token %}

    <div id="app">
        <div class="row">
            <div class="col-md-12">
                <h2 class="text-center text-primary text-center">Найдено фотографий [[ totalPhotos ]]</h2>
                <form action="" v-on:submit.prevent="searchImage">
                    <input type="text" v-model="searchQuery" class="form-control" placeholder="Search...">
                </form>
            </div>
        </div>

        <br>

        <div class="row">
            <div class="col-md-2">
                <button class="btn btn-outline-success btn-block" v-on:click="getPrevPage">&larr;</button>
            </div>
            <div class="col-md-8" style="text-align: center">
                <span class="text-info">Страница [[ currentPage ]] из [[ totalPages ]]</span>
            </div>
            <div class="col-md-2">
                <button class="btn btn-outline-success btn-block pull-right" v-on:click="getNextPage">&rarr;</button>
            </div>
        </div>

        <br>

        <div class="row">
            <div class="col-md-2">
                <div class="list-group">
                    <a
                            href="#"
                            class="list-group-item"
                            v-for="category in categories"
                            v-on:click.prevent="filterByCategory(category[0])"
                            v-bind:class="{ active: isActiveCategory(category[0]) }"
                    >[[ category[1] ]]</a>
                </div>
            </div>
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-3" v-for="photo in photos">
                        <div class="card mb-4">
                            <img class="card-img-top img-fluid" :src="photo.webformatURL">
                            <div class="card-body">
                                <button
                                        class="btn btn-outline-primary btn-block"
                                        v-on:click="addImageToMe(photo.largeImageURL, photo.id)"
                                        v-if="isInMyImages(photo.id)"
                                >+ в мои картинки</button>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted"><i class="fa fa-thumbs-o-up"></i> [[ photo.likes ]]</small>
                                <small class="text-muted pull-right"><i class="fa fa-download"></i> [[ photo.downloads ]]
                                </small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <br>

        <div class="row">
            <div class="col-md-2">
                <button class="btn btn-outline-success btn-block" v-on:click="getPrevPage">&larr;</button>
            </div>
            <div class="col-md-8" style="text-align: center">
                <span class="text-info">Страница [[ currentPage ]] из [[ totalPages ]]</span>
            </div>
            <div class="col-md-2">
                <button class="btn btn-outline-success btn-block pull-right" v-on:click="getNextPage">&rarr;</button>
            </div>
        </div>

        <br>

    </div>

{% endblock content %}

{% block footer_scripts %}
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-resource@1.5.0"></script>
    <script src="{% static '' %}images/image-search.js"></script>
{% endblock footer_scripts %}

images/templates/images/user-images-list-view.html
{% extends 'theme_2.html' %}
{% load thumbnail %}
{% load static %}

{% block page_name %}
    Список Ваших изображений
{% endblock %}

{% block page_small_name %}
    Каждая отправленная ссылка на лендинг с другим изображением повышает шанс получить нового партнёра. Действуй!
{% endblock %}

{% block help_link %}
    <a class="btn btn-outline-info" href="#">Как с этим работать?</a>
{% endblock %}

{% block content %}

    <div class="row">
        {% for user_image in images %}
            <div class="col-md-3 imageCard">
                <div class="card mb-4 card-shadow">
                    <img id="imageImage-{{ user_image.id }}" class="card-img-top img-fluid" src="{{ user_image.image.url }}" alt="{{ user_image.title }}">
                    <div class="card-body">
                        <h5 class="card-title text-center" id="imageTitle-{{ user_image.id }}">{{ user_image.title }}</h5>
                        <a class="btn btn-square btn-outline-primary btn-lg showMyLendingModal"
                                data-image="{{ user_image.id }}" href="{% url 'images:detail-image' user_image.id %}"
                        >
                            Связаные лендинги {{ user_image.count_landings }}
                        </a>
                        <a class="btn btn-square btn-outline-danger btn-lg pull-right deleteMyImage" href="{% url 'images:delete-image' user_image.pk %}">
                            <i class="ti-trash"></i>
                        </a>
                        <a class="btn btn-square btn-outline-warning btn-lg pull-right" href="{% url 'images:create-image' user_image.pk %}">
                            <i class=" icon-magic-wand "></i>
                        </a>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Last updated 3 mins ago</small>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div id="MyLendingModal" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="MyLendingModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <img src="" id="modalImage" class="img-fluid rounded">
                    <hr>
                    <ul class="list-group" id="modalListGroup"></ul>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block footer_scripts %}{% endblock footer_scripts %}