images/urls.py
from django.urls import path
from .views import (
    UserImageListView,
    CreateNewimageView,
    SearchImageView,
    DeleteImage,
    ImageDetailView,
    LandingToImage,
)


app_name = 'images'
urlpatterns = [
    path('', UserImageListView.as_view(), name='user-images-list'),
    path('image/<int:pk>/', ImageDetailView.as_view(), name='detail-image'),
    path('create-image/<int:pk>/', CreateNewimageView.as_view(), name='create-image'),
    path('delete-image/<int:pk>/', DeleteImage.as_view(), name='delete-image'),
    path('search-image/', SearchImageView.as_view(), name='search-image'),
    path('landing-to-image/', LandingToImage.as_view(), name='landing-to-image'),
]

mlm_builder/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import url
from django.views.generic import TemplateView

from landing.views import LandingDetailView
from mlm_builder.settings import MEDIA_URL, MEDIA_ROOT, DEBUG
from django.conf.urls.static import static
from dashboard_home.views import DashboardView
from webinar.views import WebinarPublicDetailView


urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('dashboard/', include([
        path('', DashboardView.as_view(), name='dashboard'),
        path('profile/', include('profile_mlm.urls')),
        path('webinar/', include('webinar.urls')),
        path('packages/', include('package.urls')),
        path('lending/', include('landing.urls')),
        path('images/', include('images.urls')),
    ])),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('l/<int:pk>/<slug:webinar_slug>/', LandingDetailView.as_view(), name='webinar-view'),
    path('l/<int:pk>/<slug:webinar_slug>/<int:image_pk>/', LandingDetailView.as_view(), name='webinar-view'),
    path('w/<slug:code>/', WebinarPublicDetailView.as_view(), name='publick-webinar'),
    re_path(r'^datetimepicker/', include('datetimepicker.urls')),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)


if DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

webinar/urls.py
from django.urls import path
from .views import (
    WebinarListView,
    WebinarDetailView,
    WebinarUpdateView,
    WebinarCreateView,
    WebinarDeleteView,
)


app_name = 'webinar'
urlpatterns = [
    path('', WebinarListView.as_view(), name='my_webinars'),
    path('<slug:slug>/<int:owner_pk>', WebinarDetailView.as_view(), name='detail'),
    path('<slug:slug>/update', WebinarUpdateView.as_view(), name='update'),
    path('<slug:slug>/delete', WebinarDeleteView.as_view(), name='delete'),
    path('create', WebinarCreateView.as_view(), name='create'),
]

landing/models.py
from django.db import models
from mlm_builder.basemodel import BaseModel
from django.contrib.auth.models import User
from django.shortcuts import reverse
from webinar.models import Webinar, WebinarUser
from django.utils.crypto import get_random_string


def set_code():
    """
    Генерация уникального кода для шаблона
    :return: str
    """
    last = Template.objects.first()
    if last is None:
        new_code = 'THEME-1'
    else:
        last_code = last.code.split('-')
        new_code = '{}-{}'.format(last_code[0], (int(last_code[1]) + 1))
    return new_code


def set_image_name(instanse, filename):
    name = get_random_string(20)
    ext = filename.split('.')[-1]
    path = 'lendings/{}__{}.{}'.format(instanse.pk, name, ext)
    return path


class Landing(BaseModel):
    """
    Лендинг привязаный к вебинару
    """
    title = models.CharField(verbose_name='Название', blank=True, null=True, max_length=250)
    description = models.CharField(verbose_name='Описание', blank=True, null=True, max_length=250)
    image = models.ImageField(verbose_name='Изображение', upload_to=set_image_name, null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    webinar = models.ForeignKey(Webinar, on_delete=models.CASCADE, verbose_name='Вебинар')
    landing_HTML = models.TextField(verbose_name='HTML код лендинга', blank=True, null=True)

    class Meta:
        verbose_name = 'Лендинг'
        verbose_name_plural = 'Лендинги'

    def __str__(self):
        if self.title:
            return self.title
        return '{} > {}'.format(self.owner, self.webinar)

    def get_absolute_url(self):
        return reverse('webinar-view', kwargs={'pk': self.id, 'webinar_slug': self.webinar.slug})

    def get_edit_premium_link(self):
        return reverse('landing:edit-premium', kwargs={'pk': self.id})

    def get_count_email(self):
        """
        Получает количество email собранных этим лендингом
        :return: int
        """
        return WebinarUser.objects.filter(landing=self).count()

    def get_userimages(self):
        from images.models import LandingImage
        userimages = LandingImage.objects.select_related(
            'userimage',
        ).filter(
            langing=self,
        )
        return userimages

webinar/models.py
from django.db import models
from mlm_builder.basemodel import BaseModel
from mlm_builder.utils import set_filename, slugify
from django.contrib.auth.models import User
from .validators import youtube_validator
from ckeditor_uploader.fields import RichTextUploadingField
from sorl.thumbnail import ImageField
import datetime
from django.shortcuts import reverse
from django.utils.crypto import get_random_string


def get_unique_code():
    code = get_random_string(8)
    exist_count = WebinarUser.objects.filter(code=code).count()
    if exist_count > 0:
        return get_unique_code()
    return code


# TODO Написать свой валидатор для Vimeo
class Webinar(BaseModel):
    """
    Модель вебинара
    """
    owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=None)
    title = models.CharField(max_length=255, verbose_name='Название')
    slug = models.SlugField(unique=True, verbose_name='Слаг', blank=True, null=True)
    description = RichTextUploadingField(verbose_name='Описание', blank=True, null=True)
    video = models.URLField(verbose_name='Видео', validators=[youtube_validator])
    image = ImageField(verbose_name='Изображение', upload_to=set_filename, blank=True, null=True)
    author = models.CharField(verbose_name='Автор', max_length=100, blank=True, null=True)
    active_start_date = models.DateTimeField(verbose_name='Дата старта показа')
    active_end_date = models.DateTimeField(verbose_name='Дата прекращения показа')
    is_moderate = models.BooleanField(default=False, verbose_name='Одобренно модератором')

    class Meta:
        verbose_name = 'Вебинар'
        verbose_name_plural = 'Вебинары'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('webinar:detail', kwargs={'slug': self.slug, 'owner_pk': self.owner.id})

    def get_video_id(self):
        from urllib.parse import urlparse
        url_data = urlparse(self.video).query
        for param in url_data.split('&'):
            if param.split('=')[0] == 'v':
                return param.split('=')[1]

    def is_webinar_active_now(self):
        """
        Проверяет доступность вебинара на момент запроса 
        :return: bool
        """
        now = datetime.datetime.now()
        if (
            self.active_start_date <= now
            and self.active_end_date >= now
            and self.is_moderate
        ):
            return True
        return False

    def make_unique_slug(self):
        """
        Генерация уникального СЛАГа
        """
        new_slug = slugify(self.title)
        count = 0
        while Webinar.objects.filter(slug=new_slug).exclude(id=self.id).count() > 0:
            count += 1
            new_slug = '{slug}-{count}'.format(slug=new_slug, count=count)
        self.slug = new_slug

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.make_unique_slug()
        return super(Webinar, self).save(*args, **kwargs)


class WebinarUser(BaseModel):
    """
    Модель посетителя который подписался на вебинар через конкретный лендинг
    """
    owner = models.ForeignKey(User, on_delete=None, verbose_name='Пользователь')
    webinar = models.ForeignKey(Webinar, on_delete=None, verbose_name='Вебинар')
    email = models.EmailField(verbose_name='E-mail')
    landing = models.ForeignKey('landing.Landing', on_delete=models.SET_DEFAULT, verbose_name='Ленгинг',            default=None, blank=True, null=True)
    code = models.CharField(max_length=8, verbose_name='Код', default=get_unique_code, unique=True)
    is_visit = models.BooleanField(default=False, verbose_name='Посещал вебинар')

    class Meta:
        verbose_name = 'Пользователи вебинара'
        verbose_name_plural = 'Пользователи вебинара'

    def __str__(self):
        return self.email

webinar/forms.py
from django import forms
from .models import Webinar


class WebinarUpdateForm(forms.ModelForm):

    class Meta:
        model = Webinar
        exclude = ('owner', 'is_moderate', 'slug',)
        widgets = {
            'active_start_date': forms.TextInput(attrs={'class': 'datetime'})
        }


class WebinarCreateForm(forms.ModelForm):

    class Meta:
        model = Webinar
        exclude = ('owner', 'is_moderate', 'slug',)

webinar/views.py
from django.views.generic import ListView, DetailView, UpdateView, CreateView, View
from .models import Webinar, WebinarUser
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import WebinarUpdateForm, WebinarCreateForm
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib import messages
from landing.models import Landing
from django.db.transaction import atomic


class WebinarListView(LoginRequiredMixin, ListView):
    template_name = 'webinar/webinar-list.html'
    context_object_name = 'webinars'

    def get_queryset(self):
        webinars = Webinar.objects.select_related('owner').prefetch_related('landing_set').filter(
            # is_moderate=True,
            # active_start_date__lte=datetime.datetime.now(),
            # active_end_date__gte=datetime.datetime.now(),
            owner=self.request.user,
        )
        return webinars


class WebinarPublicDetailView(View):
    template_name = 'webinar/webinar-detail.html'
    context = {}

    def get(self, request, code, **kwargs):
        webinar = WebinarUser.objects.select_related('webinar').get(code=code).webinar
        self.context['webinar'] = webinar
        return render(request, self.template_name, self.context)


class WebinarDetailView(LoginRequiredMixin, DetailView):
    template_name = 'webinar/webinar-detail.html'
    context_object_name = 'webinar'

    def get_object(self, **kwargs):

        webinar = Webinar.objects.prefetch_related('webinaruser_set').get(
            slug=self.kwargs.get('slug'),
            owner__id=self.kwargs.get('owner_pk'),
        )

        return webinar


class WebinarUpdateView(UpdateView):
    template_name = 'webinar/webinar-update.html'
    form_class = WebinarUpdateForm

    def get_object(self, **kwargs):
        return Webinar.objects.get(slug=self.kwargs.get('slug'))

    def get_success_url(self):
        return self.get_object().get_absolute_url()


class WebinarCreateView(LoginRequiredMixin, CreateView):
    template_name = 'webinar/webinar-update.html'
    form_class = WebinarCreateForm
    model = Webinar

    def get(self, request, *args, **kwargs):
        if self.request.user.profile.is_can_create_webinar():
            return super(WebinarCreateView, self).get(request, *args, **kwargs)
        else:
            messages.error(self.request, 'У Вас закончилась квота на создание вебинаров', 'danger')
            return redirect(reverse_lazy('package:list'))

    def get_success_url(self):
        return self.get_object().get_absolute_url()

    def form_valid(self, form):
        webinar = form.save(commit=False)
        webinar.owner = self.request.user
        webinar.save()
        return redirect(reverse_lazy('webinar:detail', kwargs={'slug': webinar.slug, 'owner_pk': webinar.owner.id}))


class WebinarDeleteView(View):

    def post(self, request, slug):
        webinar = Webinar.objects.get(slug=slug)
        lengings = Landing.objects.filter(webinar=webinar)

        with atomic():
            webinar.delete()
            lengings.delete()

        return JsonResponse({'success': 1})

webinar/templates/webinar/webinar-detail.html
{% extends 'theme_2.html' %}
{% load thumbnail %}
{% load static %}

{% block page_name %}
    {#    Список Ваших вебинаров#}
{% endblock %}

{% block page_small_name %}
    {#    Каждая отправленная ссылка на вебинар - это твой потенциальный новый партнер.#}
    {#    Действуй!#}
{% endblock %}

{% block help_link %}
    {#    <a class="btn btn-outline-info" href="#">#}
    {#        <i class="icon-graduation pr-2"></i>#}
    {#        Как с этим работать?#}
    {#    </a>#}
{% endblock %}

{% block content %}
    <div class="row clearfix">
        <div class="col-md-12">
            {% if webinar.is_webinar_active_now %}
                <div class="card card-shadow">
                    <div class="card-header">
                        <div class="card-title">
                            {{ webinar.title }}
                            {% if user == webinar.owner %}
                                {% include 'webinar/partials/_webinar-actions.html' with webinar=webinar %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="card-body">
                            <div data-type="youtube" data-video-id="{{ webinar.get_video_id }}"></div>
                            <br>
                            <ul class="nav nav-tabs mb-4" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="#tab_1">Описание вебинара</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" data-toggle="tab" href="#tab_2">Пользователи</a>
                                </li>
                            </ul>

                            <div class="tab-content">
                                <div class="tab-pane" id="tab_1" role="tabpanel">
                                    <p>Автор: <b>{{ webinar.author }}</b></p>
                                    <div>{{ webinar.description | safe }}</div>
                                </div>
                                <div class="tab-pane active" id="tab_2" role="tabpanel">
                                    <table id="bs4-table" class="table table-bordered table-striped"
                                           cellspacing="0" width="100%">
                                        <thead>
                                        <tr>
                                            <th>E-mail</th>
                                            <th>Посещал вебинар</th>
                                            <th>Зарегистрирван</th>
                                        </tr>
                                        </thead>
                                        <tfoot>
                                        <tr>
                                            <th>E-mail</th>
                                            <th>Посещал вебинар</th>
                                            <th>Зарегистрирван</th>
                                        </tr>
                                        </tfoot>
                                        <tbody>
                                        {% for webinar_user in webinar.webinaruser_set.all %}
                                        <tr>
                                            <td>{{ webinar_user.email }}</td>
                                            <td>{% if webinar_user.is_visit %}<span class="badge badge-success">да</span>{% else %}<span class="badge badge-danger" style="text-transform: uppercase; font-size: .8em;">нет</span>{% endif %}</td>
                                            <td>{{ webinar_user.created }}</td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="card">
                    <div class="header">
                        <h2>{{ webinar.title }}</h2>
                        {% if user == webinar.owner %}
                            {% include 'webinar/partials/_webinar-actions.html' with webinar=webinar %}
                        {% endif %}
                    </div>
                    <div class="body">
                        {% if webinar.image %}
                            <div class="text-center">
                                {% thumbnail webinar.image "300x200" crop="center" format='PNG' as im %}
                                    <img src="{{ im.url }}" alt="{{ webinar.title }}"
                                         class="img-thumbnail responsive-img m-b-15">
                                {% endthumbnail %}
                            </div>
                        {% endif %}
                        <div class="text-center">
                            <h2>Извините! <br><small>Но этот вебинар сейчас не доступен.</small></h2>
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block footer_scripts %}
    <script src="{% static 'diverse/' %}assets/vendor/data-tables/jquery.dataTables.min.js"></script>
    <script src="{% static 'diverse/' %}assets/vendor/data-tables/dataTables.bootstrap4.min.js"></script>
    <link href="{% static 'diverse/' %}assets/vendor/data-tables/dataTables.bootstrap4.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.plyr.io/2.0.18/plyr.css">
    <script src="https://cdn.plyr.io/2.0.18/plyr.js"></script>
    <script>
        plyr.setup();

        $('#bs4-table').DataTable();
    </script>

    <style>
        .plyr__controls {
            background: #555555 !important;
            padding-top: 15px !important;
        }

        button.plyr__play-large {
            padding: 30px;
        }
    </style>
{% endblock %}

webinar/templates/webinar/webinar-list.html
{% extends 'theme_2.html' %}
{% load thumbnail %}

{% block page_name %}
    Список Ваших вебинаров
{% endblock %}

{% block page_small_name %}
    Каждая отправленная ссылка на вебинар - это твой потенциальный новый партнер.
    Действуй!
{% endblock %}

{% block help_link %}
    <a class="btn btn-outline-info" href="#">
        <i class="icon-graduation pr-2"></i>
        Как с этим работать?
    </a>
{% endblock %}

{% block content %}
    <div class="row clearfix">
        <div class="col-md-12">
            {% for webinar in webinars %}
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            {{ webinar.title }}
                            {% include 'webinar/partials/_webinar-actions.html' with webinar=webinar %}
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row clearfix">
                            <div class="col-md-3">
                                {% if webinar.image %}
                                    {% thumbnail webinar.image "300x200" crop="center" format='PNG' as im %}
                                        <img src="{{ im.url }}" alt="{{ webinar.title }}"
                                             class="img-thumbnail responsive-img">
                                    {% endthumbnail %}
                                {% endif %}
                            </div>
                            <div class="col-md-6">
                                <p>Автор: <b>{{ webinar.author }}</b></p>
                                <div>{{ webinar.description | safe | truncatewords_html:20 }}</div>
                            </div>
                            <div class="col-md-3">
                                {% if webinar.is_webinar_active_now %}
                                    <div class="btn btn-success btn-block" style="cursor: inherit;">Доступен сейчас
                                    </div>
                                {% else %}
                                    <div class="btn btn-danger btn-block" style="cursor: inherit;"> Не доступен сейчас
                                    </div>
                                {% endif %}
                                <a href="{{ webinar.get_absolute_url }}"
                                   class="webinarLink btn btn-outline-info btn-block">Страница вебинара</a>

                                {% if webinar.landing_set.all.count == 1 %}
                                    {% for landing in webinar.landing_set.all %}
                                        <a target="_blank" href="{{ landing.get_absolute_url }}"
                                           class="btn btn-outline-info btn-block">Ссылка на лендинг</a>
                                    {% endfor %}
                                {% else %}
                                    <div class="btn-group show" role="group" style="width: 100%; margin-top: .5rem;">
                                    <button type="button" class="btn btn-outline-info btn-block dropdown-toggle"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                        Ссылки на лендинги
                                    </button>
                                    <div class="dropdown-menu" x-placement="bottom-start" style="width: 100%; position: absolute; transform: translate3d(0px, 35px, 0px); top: 0px; left: 0px; will-change: transform;">
                                        {% for landing in webinar.landing_set.all %}
                                            <a class="dropdown-item" href="{{ landing.get_absolute_url }}">Лендинг
                                                №{{ forloop.counter }}</a>
                                        {% endfor %}
                                        </ul>
                                    </div>
                                {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-header" style="background: #f6f6f6;">
                        <div class="webinar__date__info">
                            <div class="row">
                                <div class="col-md-6">Дата старта показа: <b>{{ webinar.active_start_date }}</b></div>
                                <div class="col-md-6 text-right">
                                    Дата окончания показа:
                                    <b>{{ webinar.active_end_date }}</b>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

webinar/templates/webinar/webinar-update.html
{% extends 'theme_2.html' %}
{% load static %}
{% load i18n %}


{% block content %}

    <div class="row clearfix" id="webinarUpdateForm">
        <div class="col-md-12">
            <div class="card card-shadow">
                <div class="card-header">
                    {% if webinar %}
                    <div class="card-title">{{ webinar.title }}</div>
                    {% else %}
                        <div class="card-title">Создание нового вебинара</div>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                <div class="form-line {% if field.errors %}error{% endif %}">
                                    {{ field }}
                                </div>
                            </div>
                            <div class="error forms__errors">{{ field.errors }}</div>
                        {% endfor %}
                        <button class="btn btn-success btn-lg">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer_scripts %}
    {% get_current_language as LANGUAGE_CODE %}
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

    <script>

    $("#id_active_start_date, #id_active_end_date").datetimepicker({
        timepicker: true,
        format: 'd.m.Y H:i',
        lang:'ru',
        minDate: new Date()
    });

    </script>
{% endblock %}